// Consolidated HTML→text extraction.
//
// Three divergent copies used to live in toc.ts (heading labels), in
// build-static-assets.ts (llms.txt) and in search/minimatch-build.ts (search
// index). They disagreed on which blocks to drop, which entities to decode and
// whether tags became spaces or nothing. This module is the one implementation:
// every caller drops script/style/nav, decodes named + numeric entities and
// collapses whitespace; `mainOnly` is the only policy knob.

const BLOCKS_TO_DROP: RegExp[] = [
  /<script\b[^>]*>[\s\S]*?<\/script>/gi,
  /<style\b[^>]*>[\s\S]*?<\/style>/gi,
  /<nav\b[^>]*>[\s\S]*?<\/nav>/gi,
];

const NAMED_ENTITIES: ReadonlyArray<readonly [RegExp, string]> = [
  [/&amp;/g, "&"],
  [/&lt;/g, "<"],
  [/&gt;/g, ">"],
  [/&quot;/g, '"'],
  [/&#39;/g, "'"],
  [/&#x27;/g, "'"],
  [/&#x60;/g, "`"],
  [/&#x2F;/g, "/"],
];

/** The `<main>` content of a page, or `undefined` when the page has none. */
function mainContent(html: string): string | undefined {
  return html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1];
}

/**
 * HTML string → readable plain text.
 *
 * Best-effort by design: the pages being scraped are generated by this very
 * project (satteri markdown + Vincle JSX), so the tag shapes are known. It is
 * a fallback for the post-string pipeline (TOC labels, llms.txt, search
 * index) — not a substitute for walking the VNode tree.
 */
export function htmlToText(html: string, options?: { mainOnly?: boolean }): string {
  let body = options?.mainOnly ? (mainContent(html) ?? html) : html;
  for (const re of BLOCKS_TO_DROP) body = body.replace(re, " ");
  body = body.replace(/<[^>]+>/g, " ");
  for (const [re, value] of NAMED_ENTITIES) body = body.replace(re, value);
  body = body
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h: string) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, c: string) => String.fromCodePoint(Number(c)));
  return body.replace(/\s+/g, " ").trim();
}
